import {
  ProcurementSchedule,
  ProcurementSlot,
  ProcurementBooking,
  MarketplaceListing,
  MarketplaceBid,
  MarketplaceOrder,
  MandiPriceItem,
  OrderReview
} from './types';

// Pre-seeded Procurement Schedules (SIH26032)
export const INITIAL_SCHEDULES: ProcurementSchedule[] = [
  {
    id: 'SCH-1',
    mandiName: 'Shivpuri Krishi Upaj Mandi Samiti',
    district: 'Shivpuri',
    state: 'Madhya Pradesh',
    crop: 'Wheat (Sharbati & Lokwan)',
    date: '2026-09-11',
    startTime: '08:00 AM',
    endTime: '05:00 PM',
    slotDurationMinutes: 90,
    totalCapacityQuintals: 3000,
    availableCapacityQuintals: 1850,
    mspRate: 2425,
    status: 'active',
  },
  {
    id: 'SCH-2',
    mandiName: 'Shivpuri Krishi Upaj Mandi Samiti',
    district: 'Shivpuri',
    state: 'Madhya Pradesh',
    crop: 'Mustard (High Oil Grade)',
    date: '2026-09-11',
    startTime: '08:30 AM',
    endTime: '04:30 PM',
    slotDurationMinutes: 60,
    totalCapacityQuintals: 1500,
    availableCapacityQuintals: 620,
    mspRate: 5950,
    status: 'active',
  },
  {
    id: 'SCH-3',
    mandiName: 'Kolaras Sub-Mandi Yard',
    district: 'Shivpuri',
    state: 'Madhya Pradesh',
    crop: 'Soybean (Grade-A Yellow)',
    date: '2026-09-12',
    startTime: '09:00 AM',
    endTime: '06:00 PM',
    slotDurationMinutes: 90,
    totalCapacityQuintals: 2500,
    availableCapacityQuintals: 2100,
    mspRate: 4892,
    status: 'active',
  },
  {
    id: 'SCH-4',
    mandiName: 'Khanna Grain Market (Asia largest Mandi)',
    district: 'Ludhiana',
    state: 'Punjab',
    crop: 'Wheat (HD-3086)',
    date: '2026-09-11',
    startTime: '07:30 AM',
    endTime: '06:30 PM',
    slotDurationMinutes: 60,
    totalCapacityQuintals: 5000,
    availableCapacityQuintals: 2400,
    mspRate: 2425,
    status: 'active',
  }
];

export const INITIAL_SLOTS: Record<string, ProcurementSlot[]> = {
  'SCH-1': [
    {
      id: 'SLOT-1-1',
      scheduleId: 'SCH-1',
      timeWindow: '08:00 AM - 09:30 AM',
      capacityQuintals: 600,
      bookedQuintals: 450,
      remainingQuintals: 150,
      status: 'filling_fast',
    },
    {
      id: 'SLOT-1-2',
      scheduleId: 'SCH-1',
      timeWindow: '09:30 AM - 11:00 AM',
      capacityQuintals: 600,
      bookedQuintals: 600,
      remainingQuintals: 0,
      status: 'booked',
    },
    {
      id: 'SLOT-1-3',
      scheduleId: 'SCH-1',
      timeWindow: '11:00 AM - 12:30 PM',
      capacityQuintals: 600,
      bookedQuintals: 100,
      remainingQuintals: 500,
      status: 'available',
    },
    {
      id: 'SLOT-1-4',
      scheduleId: 'SCH-1',
      timeWindow: '01:30 PM - 03:00 PM',
      capacityQuintals: 600,
      bookedQuintals: 0,
      remainingQuintals: 600,
      status: 'available',
    },
    {
      id: 'SLOT-1-5',
      scheduleId: 'SCH-1',
      timeWindow: '03:00 PM - 04:30 PM',
      capacityQuintals: 600,
      bookedQuintals: 0,
      remainingQuintals: 600,
      status: 'available',
    },
  ],
  'SCH-2': [
    {
      id: 'SLOT-2-1',
      scheduleId: 'SCH-2',
      timeWindow: '08:30 AM - 10:00 AM',
      capacityQuintals: 375,
      bookedQuintals: 300,
      remainingQuintals: 75,
      status: 'filling_fast',
    },
    {
      id: 'SLOT-2-2',
      scheduleId: 'SCH-2',
      timeWindow: '10:00 AM - 11:30 AM',
      capacityQuintals: 375,
      bookedQuintals: 375,
      remainingQuintals: 0,
      status: 'booked',
    },
    {
      id: 'SLOT-2-3',
      scheduleId: 'SCH-2',
      timeWindow: '12:00 PM - 01:30 PM',
      capacityQuintals: 375,
      bookedQuintals: 150,
      remainingQuintals: 225,
      status: 'available',
    },
    {
      id: 'SLOT-2-4',
      scheduleId: 'SCH-2',
      timeWindow: '02:30 PM - 04:00 PM',
      capacityQuintals: 375,
      bookedQuintals: 55,
      remainingQuintals: 320,
      status: 'available',
    },
  ],
};

export const INITIAL_BOOKINGS: ProcurementBooking[] = [
  {
    id: 'BK-001',
    bookingCode: 'KS-MP-8419',
    farmerName: 'Rameshwar Singh Patel (आप)',
    farmerPhone: '+91 98261 44520',
    crop: 'Wheat (Sharbati & Lokwan)',
    mandiName: 'Shivpuri Krishi Upaj Mandi Samiti',
    date: '2026-09-11',
    timeSlot: '11:00 AM - 12:30 PM',
    quantityQuintals: 45,
    status: 'booked',
    bookedAt: '2026-09-10 08:30 AM',
    estimatedPayout: 109125, // 45 * 2425
  },
  {
    id: 'BK-002',
    bookingCode: 'KS-MP-7123',
    farmerName: 'Harpreet Singh Dhillon',
    farmerPhone: '+91 98150 77124',
    crop: 'Mustard (High Oil Grade)',
    mandiName: 'Shivpuri Krishi Upaj Mandi Samiti',
    date: '2026-09-11',
    timeSlot: '08:30 AM - 10:00 AM',
    quantityQuintals: 30,
    status: 'arrived',
    bookedAt: '2026-09-09 02:15 PM',
    estimatedPayout: 178500, // 30 * 5950
  },
  {
    id: 'BK-003',
    bookingCode: 'KS-MP-5520',
    farmerName: 'Dharmendra Lodhi',
    farmerPhone: '+91 94251 90812',
    crop: 'Wheat (Lokwan)',
    mandiName: 'Kolaras Sub-Mandi Yard',
    date: '2026-09-08',
    timeSlot: '10:00 AM - 11:30 AM',
    quantityQuintals: 60,
    status: 'completed',
    bookedAt: '2026-09-07 10:00 AM',
    estimatedPayout: 145500,
  }
];

// SIH26033: Direct Marketplace Listings
export const INITIAL_MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: 'LIST-1',
    farmerId: 'F-101',
    farmerName: 'Rameshwar Singh Patel (आप)',
    farmerLocation: 'Pohari Block, Shivpuri, MP',
    farmerPhone: '+91 98261 44520',
    cropName: 'Organic Sharbati Wheat',
    variety: 'C-306 Golden Amber',
    quantityQuintals: 80,
    minBasePricePerQuintal: 2750,
    mandiMspReference: 2425,
    harvestDate: '2026-03-28',
    qualityGrade: 'A+',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80'],
    status: 'active',
    createdAt: '2026-09-08',
    bidsCount: 3,
    highestBidPrice: 2980,
  },
  {
    id: 'LIST-2',
    farmerId: 'F-102',
    farmerName: 'Vikram Yadav',
    farmerLocation: 'Badarwas, Shivpuri, MP',
    farmerPhone: '+91 97520 33819',
    cropName: 'Mustard (Pusa Bold)',
    variety: 'Oil content 42.5%',
    quantityQuintals: 50,
    minBasePricePerQuintal: 6050,
    mandiMspReference: 5950,
    harvestDate: '2026-04-05',
    qualityGrade: 'A',
    images: ['https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=600&q=80'],
    status: 'active',
    createdAt: '2026-09-09',
    bidsCount: 2,
    highestBidPrice: 6200,
  },
  {
    id: 'LIST-3',
    farmerId: 'F-103',
    farmerName: 'Gurdeep Singh Sandhu',
    farmerLocation: 'Samrala, Ludhiana, Punjab',
    farmerPhone: '+91 98720 11928',
    cropName: 'Basmati Rice (Pusa 1121 Extra Long)',
    variety: 'Aged 12 Months',
    quantityQuintals: 120,
    minBasePricePerQuintal: 4200,
    mandiMspReference: 3800,
    harvestDate: '2026-01-15',
    qualityGrade: 'A+',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80'],
    status: 'active',
    createdAt: '2026-09-07',
    bidsCount: 4,
    highestBidPrice: 4450,
  },
  {
    id: 'LIST-4',
    farmerId: 'F-104',
    farmerName: 'Santosh Meena',
    farmerLocation: 'Karera, Shivpuri, MP',
    farmerPhone: '+91 94250 88201',
    cropName: 'Yellow Soybean (JS 9560)',
    variety: 'Cleaned & Graded',
    quantityQuintals: 65,
    minBasePricePerQuintal: 5100,
    mandiMspReference: 4892,
    harvestDate: '2026-04-10',
    qualityGrade: 'A',
    images: ['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80'],
    status: 'active',
    createdAt: '2026-09-09',
    bidsCount: 1,
    highestBidPrice: 5250,
  },
];

export const INITIAL_MARKETPLACE_BIDS: MarketplaceBid[] = [
  {
    id: 'BID-101',
    listingId: 'LIST-1',
    retailerId: 'RET-01',
    retailerName: 'Amit Aggarwal (AgroRetail)',
    retailerCompany: 'Aggarwal Flour Mills & Exports',
    retailerPhone: '+91 7512 449201',
    bidPricePerQuintal: 2980,
    offeredQuantityQuintals: 80,
    status: 'pending',
    createdAt: '2026-09-09 11:20 AM',
    distanceKm: 18,
    paymentMode: 'Direct DBT',
  },
  {
    id: 'BID-102',
    listingId: 'LIST-1',
    retailerId: 'RET-02',
    retailerName: 'Pooja Verma',
    retailerCompany: 'Organic Mandi Sourcing Hub',
    retailerPhone: '+91 7552 901234',
    bidPricePerQuintal: 2900,
    offeredQuantityQuintals: 80,
    status: 'pending',
    createdAt: '2026-09-09 03:45 PM',
    distanceKm: 42,
    paymentMode: 'Escrow',
  },
  {
    id: 'BID-103',
    listingId: 'LIST-1',
    retailerId: 'RET-03',
    retailerName: 'Sanjay Jain',
    retailerCompany: 'Kisan Shakti Grain Traders',
    retailerPhone: '+91 7312 882190',
    bidPricePerQuintal: 2820,
    offeredQuantityQuintals: 50,
    status: 'pending',
    createdAt: '2026-09-08 04:10 PM',
    distanceKm: 25,
    paymentMode: 'Direct DBT',
  },
  {
    id: 'BID-201',
    listingId: 'LIST-2',
    retailerId: 'RET-04',
    retailerName: 'Deepak Singhania',
    retailerCompany: 'Pure Mustard Oil Extraction Ltd',
    retailerPhone: '+91 7512 390111',
    bidPricePerQuintal: 6200,
    offeredQuantityQuintals: 50,
    status: 'pending',
    createdAt: '2026-09-09 01:15 PM',
    distanceKm: 15,
    paymentMode: 'Direct DBT',
  },
];

export const INITIAL_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ORD-901',
    orderNumber: 'KS-ORD-2026-081',
    listingId: 'LIST-1',
    cropName: 'Organic Sharbati Wheat',
    quantityQuintals: 50,
    agreedPricePerQuintal: 2950,
    totalAmount: 147500,
    farmerName: 'Rameshwar Singh Patel (आप)',
    farmerPhone: '+91 98261 44520',
    retailerName: 'Amit Aggarwal',
    retailerCompany: 'Aggarwal Flour Mills & Exports',
    status: 'paid',
    paidAt: '2026-09-06 02:40 PM',
    paymentReference: 'UPI/DBT-942817291039',
    createdDate: '2026-09-05',
  },
  {
    id: 'ORD-902',
    orderNumber: 'KS-ORD-2026-077',
    listingId: 'LIST-3',
    cropName: 'Basmati Rice (Pusa 1121)',
    quantityQuintals: 80,
    agreedPricePerQuintal: 4400,
    totalAmount: 352000,
    farmerName: 'Gurdeep Singh Sandhu',
    farmerPhone: '+91 98720 11928',
    retailerName: 'Sanjay Jain',
    retailerCompany: 'Kisan Shakti Grain Traders',
    status: 'completed',
    paidAt: '2026-09-03 11:15 AM',
    paymentReference: 'IMPS/DBT-881920194820',
    createdDate: '2026-09-02',
  },
];

// Live Mandi Prices from Agmarknet / data.gov.in standard format
export const INITIAL_MANDI_PRICES: MandiPriceItem[] = [
  {
    id: 'MP-01',
    state: 'Madhya Pradesh',
    district: 'Shivpuri',
    marketName: 'Shivpuri APMC Mandi',
    commodity: 'Wheat (गेहूं)',
    variety: 'Sharbati / Lokwan',
    arrivalDate: 'Today (आज)',
    minPrice: 2450,
    maxPrice: 2980,
    modalPrice: 2750,
    mspRate: 2425,
    trend: 'up',
    changeAmount: 65,
  },
  {
    id: 'MP-02',
    state: 'Madhya Pradesh',
    district: 'Shivpuri',
    marketName: 'Shivpuri APMC Mandi',
    commodity: 'Mustard (सरसों)',
    variety: 'Black Bold',
    arrivalDate: 'Today (आज)',
    minPrice: 5850,
    maxPrice: 6250,
    modalPrice: 6100,
    mspRate: 5950,
    trend: 'up',
    changeAmount: 120,
  },
  {
    id: 'MP-03',
    state: 'Madhya Pradesh',
    district: 'Shivpuri',
    marketName: 'Kolaras Mandi',
    commodity: 'Soybean (सोयाबीन)',
    variety: 'Yellow Grade-1',
    arrivalDate: 'Today (आज)',
    minPrice: 4700,
    maxPrice: 5350,
    modalPrice: 5150,
    mspRate: 4892,
    trend: 'up',
    changeAmount: 40,
  },
  {
    id: 'MP-04',
    state: 'Punjab',
    district: 'Ludhiana',
    marketName: 'Khanna APMC Mandi',
    commodity: 'Wheat (गेहूं)',
    variety: 'PBW 725 / HD 3086',
    arrivalDate: 'Today (आज)',
    minPrice: 2425,
    maxPrice: 2600,
    modalPrice: 2520,
    mspRate: 2425,
    trend: 'stable',
    changeAmount: 10,
  },
  {
    id: 'MP-05',
    state: 'Punjab',
    district: 'Amritsar',
    marketName: 'Amritsar Grain Market',
    commodity: 'Basmati Rice (बासमती)',
    variety: 'Pusa 1121 Extra Long',
    arrivalDate: 'Today (आज)',
    minPrice: 3950,
    maxPrice: 4600,
    modalPrice: 4350,
    mspRate: 3800,
    trend: 'up',
    changeAmount: 180,
  },
  {
    id: 'MP-06',
    state: 'Maharashtra',
    district: 'Nashik',
    marketName: 'Lasalgaon Mandi',
    commodity: 'Onion (प्याज)',
    variety: 'Red Medium',
    arrivalDate: 'Today (आज)',
    minPrice: 1800,
    maxPrice: 2650,
    modalPrice: 2200,
    mspRate: 1750,
    trend: 'down',
    changeAmount: -50,
  },
  {
    id: 'MP-07',
    state: 'Rajasthan',
    district: 'Kota',
    marketName: 'Bhamashah Mandi Kota',
    commodity: 'Coriander / Dhaniya (धनिया)',
    variety: 'Badami Green',
    arrivalDate: 'Today (आज)',
    minPrice: 6800,
    maxPrice: 7900,
    modalPrice: 7400,
    mspRate: 6500,
    trend: 'up',
    changeAmount: 210,
  },
];

// Order Reviews & Trust Network
export const INITIAL_REVIEWS: OrderReview[] = [
  {
    id: 'REV-1',
    orderId: 'ORD-901',
    reviewerId: 'RET-01',
    reviewerName: 'Amit Aggarwal (Aggarwal Flour Mills)',
    reviewerRole: 'retailer',
    revieweeName: 'Rameshwar Singh Patel (Farmer)',
    rating: 5,
    comment: 'उत्कृष्ट गुणवत्ता का शरबती गेहूं! नमी की मात्रा मात्र 10.5% थी और तुलाई में पूर्ण पारदर्शिता रही। तत्काल भुगतान कर दिया गया।',
    createdAt: '2026-09-06',
    verifiedTransaction: true,
  },
  {
    id: 'REV-2',
    orderId: 'ORD-901',
    reviewerId: 'F-101',
    reviewerName: 'Rameshwar Singh Patel (Farmer)',
    reviewerRole: 'farmer',
    revieweeName: 'Amit Aggarwal (Buyer)',
    rating: 5,
    comment: 'बिना किसी बिचौलिए के MSP से ₹525 ज्यादा मिला और गाड़ी खाली होते ही 2 घंटे में खाते में पूरा पैसा आ गया। बहुत शानदार व्यवस्था!',
    createdAt: '2026-09-06',
    verifiedTransaction: true,
  },
  {
    id: 'REV-3',
    orderId: 'ORD-902',
    reviewerId: 'F-103',
    reviewerName: 'Gurdeep Singh Sandhu (Farmer)',
    reviewerRole: 'farmer',
    revieweeName: 'Sanjay Jain (Kisan Shakti Traders)',
    rating: 5,
    comment: 'Pusa 1121 Basmati fair weighment and direct online payment on time. No deduction or hidden cuts.',
    createdAt: '2026-09-03',
    verifiedTransaction: true,
  }
];
